# Generated by Django 3.2 on 2021-06-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='간단소개')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='자격증명')),
                ('regiNum', models.CharField(max_length=30, verbose_name='자격증번호')),
                ('issure', models.CharField(max_length=30, verbose_name='발급처')),
                ('dateAcq', models.DateField(verbose_name='취득일')),
                ('signature', models.CharField(blank=True, max_length=10, verbose_name='인증')),
                ('domain', models.URLField(blank=True, verbose_name='이더넷')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='직무')),
                ('company', models.CharField(max_length=30, verbose_name='회사/장소')),
                ('text', models.TextField(verbose_name='당시 한 일')),
                ('dateFrom', models.DateField(verbose_name='시작일')),
                ('dateEnd', models.DateField(verbose_name='종료일')),
                ('signature', models.CharField(blank=True, max_length=10, verbose_name='인증')),
                ('domain', models.URLField(blank=True, verbose_name='이더넷')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30, verbose_name='학교명')),
                ('major', models.CharField(max_length=30, null=True, verbose_name='전공명')),
                ('dateEnd', models.DateField(verbose_name='종료일')),
                ('GPA', models.CharField(max_length=5, verbose_name='학점')),
                ('signature', models.CharField(blank=True, max_length=10, verbose_name='인증')),
                ('domain', models.URLField(blank=True, verbose_name='이더넷')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
        ),
    ]
