# Generated by Django 3.2 on 2021-05-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='resumes/files/%Y/%m/%d'),
        ),
    ]
