# Generated by Django 3.2 on 2021-06-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='signature',
            field=models.BooleanField(default=False, verbose_name='인증'),
        ),
    ]
