# Generated by Django 3.2 on 2021-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20210512_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfintro',
            name='text',
            field=models.TextField(verbose_name='간단소개'),
        ),
    ]
