# Generated by Django 3.2 on 2021-05-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_file_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
    ]
