# Generated by Django 3.2 on 2021-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='AddSNS',
        ),
        migrations.AlterField(
            model_name='sns',
            name='blog',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
