# Generated by Django 3.2 on 2021-05-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210512_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sns',
            old_name='profile',
            new_name='user_id',
        ),
    ]
