# Generated by Django 3.2 on 2021-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='capName',
        ),
        migrations.AlterField(
            model_name='company',
            name='compName',
            field=models.CharField(max_length=30, verbose_name='기관명'),
        ),
    ]
