# Generated by Django 3.2 on 2021-05-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210513_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
